name: Helm Chart Validator
description: Lint and dry-run Helm charts

inputs:
  chart-path:
    required: true
    description: Path to the Helm chart
  release-name:
    required: false
    default: "test-release"
  namespace:
    required: false
    default: "default"

runs:
  using: "composite"
  steps:
    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: v3.14.0

    - name: Install kubeconform
      shell: bash
      run: |
        curl -L https://github.com/yannh/kubeconform/releases/latest/download/kubeconform-linux-amd64.tar.gz \
        | tar xz && sudo mv kubeconform /usr/local/bin/

    - name: Helm Lint
      shell: bash
      run: helm lint "${{ inputs.chart-path }}"

    - name: Helm Dry Run Template
      shell: bash
      run: |
        helm template $(${{ inputs.release-name }} | cut -d/ -f2) ${{ inputs.chart-path }} \
          --values ${{ inputs.chart-path }}/values.yaml \
          --namespace ${{ inputs.namespace }}

    - name: Validate with kubeconform
      shell: bash
      run: |
        helm template ${{ inputs.release-name }} ${{ inputs.chart-path }} \
          --values ${{ inputs.chart-path }}/values.yaml \
          --namespace ${{ inputs.namespace }} \
          | kubeconform -strict -summary
            --namespace ${{ inputs.namespace }} \
            | kubeconform -strict -summary
