apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applicationset
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/kapyuval/msd-test-helm.git
        revision: main
        directories:
          - path: apps/prometheus/*
  template:
    metadata:
      name: prometheus-{{path.basename}}
    spec:
      project: default
      source:
        repoURL: https://prometheus-community.github.io/helm-charts
        chart: kube-prometheus-stack
        targetRevision: 76.4.0  # example version
        helm:
          valueFiles:
            - values.yaml
      destination:
        name: in-cluster
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
