apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kapyuval/msd-test-helm.git
    targetRevision: main
    path: root-app
    directory:
      recurse: true
  destination:
    server: in-cluster
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
