apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ include "msd-test-app.fullname" . }}
  namespace: argocd
spec:
  scaleTargetRef:
    name: {{ include "msd-test-app.fullname" . }}
  minReplicaCount: {{ .Values.autoscaling.minReplicas }}
  maxReplicaCount: {{ .Values.autoscaling.maxReplicas }}
  cooldownPeriod: 300
  triggers:
    - type: prometheus
      metadata:
        serverAddress: {{ .Values.autoscaling.triggers.serverAddress }}
        metricName: msd_cpu_limit_reached_pods
        query: >
          count by (pod) (
            (
              count by (pod) (
                (
                  rate(container_cpu_usage_seconds_total{container!="POD", image=~".*{{ include "msd-test-app.fullname" . }}.*"}[5m])
                  /
                  kube_pod_container_resource_limits_cpu_cores{container!="POD"}
                ) > 0.9
              )
              ==
              count by (pod) (
                kube_pod_container_resource_limits_cpu_cores{container!="POD", image=~".*{{ include "msd-test-app.fullname" . }}.*"}
              )
            )
          )
        threshold: "{{ .Values.autoscaling.triggers.threshold }}"