apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ingress.yaml

helmCharts:
  - name: kube-prometheus-stack
    repo: https://prometheus-community.github.io/helm-charts
    version: 76.4.0
    releaseName: kube-prometheus-stack
    valuesFile: values.yaml
    namespace: argocd
