apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

helmCharts:
  - name: prometheus
    repo: https://prometheus-community.github.io/helm-charts
    version: 76.4.0
    releaseName: prometheus
    valuesFile: values.yaml
