name: Helm Validate Reusable Workflow

on:
  workflow_call:
    inputs:
      chart-path:
        required: true
        type: string
      release-name:
        required: false
        type: string
        default: "test-release"
      namespace:
        required: false
        type: string
        default: "default"

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.14.0

      - name: Install kubeconform
        run: |
          curl -L https://github.com/yannh/kubeconform/releases/latest/download/kubeconform-linux-amd64.tar.gz \
            | tar xz
          sudo mv kubeconform /usr/local/bin/

      - name: Helm lint
        run: helm lint ${{ inputs.chart-path }}

      - name: Helm dry run (template)
        run: |
          helm template ${{ inputs.release-name }} ${{ inputs.chart-path }} \
            --values ${{ inputs.chart-path }}/values.yaml \
            --namespace ${{ inputs.namespace }}

      - name: Validate rendered templates with kubeconform
        run: |
          helm template ${{ inputs.release-name }} ${{ inputs.chart-path }} \
            --values ${{ inputs.chart-path }}/values.yaml \
            --namespace ${{ inputs.namespace }} \
            | kubeconform -strict -summary
